server:
  port: 8282

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128
  # 服务名
  application:
    name: service-mq
  # redis配置
  redis:
    host: 192.168.200.128
    port: 6379
  # rabbitmq配置
  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: guest
    password: guest
    #virtual-host: /
    publisher-confirm-type: simple # 确认机制
    publisher-returns: true # 开启回调
    listener:
      simple:
        acknowledge-mode: manual # 默认情况下消息消费者是自动确认消息的，如果要手动确认消息则需要修改确认模式为manual
      direct:
        prefetch: 1 # 消费者每次从队列获取的消息数量。此属性当不设置时为：轮询分发，设置为1为：公平分发




















