server:
  port: 8083

# mysql数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  # nacos地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.128
#  # 服务名
#  application:
#    name: service-product
  # redis配置
  redis:
    host: 192.168.200.128
    port: 6379
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-idle: 5 #最大空闲
        min-idle: 0 #最小空闲
        max-wait: -1 #最大阻塞等待时间(负数代表)
#
## mybatis
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true # 驼峰命名
#  mapper-locations: classpath:mapper/*Mapper.xml # mapper路径

#fileServer:
#url: http://42.192.250.48:80/

