spring:
  thymeleaf:
    cache: false
    mode: HTML5 #使语法校验不像java那么严格
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128
  # 服务名
  application:
    name: web-all

server:
  port: 8300

# feign超时设置
feign:
  client:
    config:
      default:
        connectTimeout: 600000 # 一小时
        readTimeout: 600000