server:
  port: 8202

spring:
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128
  # 服务名
  application:
    name: service-item

# feign超时设置
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000