server:
  port: 8080

# mysql数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128
  # 服务名
  application:
    name: service-product
  # redis配置
  redis:
    host: 192.168.200.128
    port: 6379

# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
  mapper-locations: classpath:mapper/*.xml # mapper路径

#fileServer:
#url: http://42.192.250.48:80/

# feign超时设置
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000

