server:
  port: 8080

# mysql数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.200.128/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
  mapper-locations: classpath:mapper/*Mapper.xml # mapper路径
